[paths]
local_folder = <> # Path to the local folder where the project is stored

; Base directory for models
models_dir = <> # Path to the directory where models are stored

[models]
; Base models
qwen_8b = Qwen/Qwen-8B
llama_3_3_70b_instruct = meta-llama/Meta-Llama-3-70B-Instruct

[model_aliases]
; Shortcuts for commonly used models
l_70i = llama_3_3_70b_instruct
q_8i = qwen_8b

[defaults]
; Default models to use when not specified
default_model = qwen_8b
