from typing import Dict, List, Union, Any

from evaluate import RELATION_TYPE

def post_process_generated_text(
    generated_text: str, 
    prompt: str, 
    stop_string: str = "\n\nQ:", 
    cot: bool = False, 
    verbose: bool = False, 
    experiment: Any = None, 
    subject_entity: str = "", 
    relation: str = "", 
    is_train: bool = False
) -> str:
    """
    Post-process the generated text in the legacy format.
    
    Args:
        generated_text: Full generated text including prompt
        prompt: Original prompt to remove
        stop_string: String to truncate at
        cot: Whether chain-of-thought was used
        verbose: Whether to log details
        experiment: Experiment object for logging
        subject_entity: Subject entity for logging
        relation: Relation for logging
        is_train: Whether this is training data
        
    Returns:
        str: Post-processed generated text
    """
    # Remove prompt prefix
    generated_text = generated_text[len(prompt):].strip()
    
    # Truncate at stop string if present
    if stop_string in generated_text:
        generated_text = generated_text.split(stop_string)[0].strip()
    
    # Handle chain-of-thought
    cot_text = ""
    if cot:
        start_seq = "<think>"
        end_seq = "</think>"
        if end_seq in generated_text:
            cot_text = generated_text.split(start_seq)[1].split(end_seq)[0].strip() if start_seq in generated_text else ""
            generated_text = generated_text.split(end_seq)[-1].strip() if end_seq in generated_text else generated_text
    
    # Log if requested
    if verbose and experiment:
        experiment.log_generation(prompt, cot_text, generated_text, subject_entity, relation, is_train)
    
    return generated_text

def format_for_display(prompt: Union[str, List[Dict[str, str]]], tokenizer=None) -> str:
    """
    Format a prompt or chat messages for human-readable display.
    
    Args:
        prompt: String prompt or list of chat messages
        tokenizer: Tokenizer (unused, for compatibility)
        
    Returns:
        str: Formatted prompt for display
    """
    if isinstance(prompt, list):  # Chat format
        formatted = ""
        for msg in prompt:
            role = msg["role"].upper()
            content = msg["content"]
            formatted += f"[{role}]: {content}\n\n"
        return formatted.strip()
    else:  # Standard text prompt
        return prompt

def classify_answer_quality(tp_items, fp_items, fn_items, has_think_tags=True):
    """
    Classify the quality of a generated answer compared to ground truth.
    
    Args:
        tp_items: List of true positive items (correctly found)
        fp_items: List of false positive items (hallucinated)
        fn_items: List of false negative items (missed)
        has_think_tags: Whether the answer has proper <think></think> tags (for CoT)
        
    Returns:
        str: Classification of answer quality:
            - "correct": All answers are correct, nothing missed
            - "incomplete": All answers are correct, but some missing (must have at least one correct answer)
            - "wrong": Some answers are incorrect or missing all answers when there should be some
            - "failed": Missing required think tags
            - "other": Other failure case
    """
    # Check for missing think tags when required
    if has_think_tags is False:
        return "failed"
    
    # Check for wrong answers (hallucinations)
    if len(fp_items) > 0:
        return "wrong"
    
    # Empty prediction when there should be answers is wrong
    if len(tp_items) == 0 and len(fn_items) > 0:
        return "wrong"
    
    # Incomplete: some correct answers but missing others
    if len(tp_items) > 0 and len(fn_items) > 0:
        return "incomplete"
    
    # At this point either:
    # 1. tp > 0, fn = 0: found all answers
    # 2. tp = 0, fn = 0: correctly predicted empty when target is empty
    return "correct"

def evaluate_generated_answer(
    generated_text: str,
    true_objects: list,
    normalize: bool = True,
    extract_answer: bool = True,
    require_think_tags: bool = False,
    relation: str = None,
    tolerance: float = 0.05
) -> dict:
    """
    Evaluate the quality of a generated answer compared to ground truth.
    
    Args:
        generated_text: The text generated by the model
        true_objects: List of correct object entities
        normalize: Whether to normalize text for matching (lowercase, strip)
        extract_answer: Whether to extract answer from CoT (after </think> tag)
        require_think_tags: Whether to require <think></think> tags
        relation: The relation type to determine if numerical tolerance should be applied
        tolerance: Tolerance for numerical comparisons (default 5%)
        
    Returns:
        dict: Evaluation metrics including:
            - extracted_answer: The extracted answer text
            - tp_items: List of true positive items (correctly found)
            - fp_items: List of false positive items (hallucinated)
            - fn_items: List of false negative items (missed)
            - quality: Classification of answer quality
            - precision: Precision score
            - recall: Recall score
            - f1: F1 score
    """
    # Check for required think tags
    has_think_tags = True
    if require_think_tags:
        if "<think>" not in generated_text or "</think>" not in generated_text:
            has_think_tags = False
    
    # Extract answer if needed (for CoT responses)
    if extract_answer:
        if "</think>" in generated_text:
            answer_text = generated_text.split("</think>", 1)[1].strip()
            
            # Handle case where model stops after </think> tag or just says "None"
            if not answer_text or answer_text.lower() == "none":
                answer_text = ""  # Treat as empty prediction
        else:
            # When no </think> tag is found, use empty string
            answer_text = ""
    else:
        answer_text = generated_text.strip()
    
    # Process the answer text to recognize empty answers
    is_empty_answer = (
        not answer_text or 
        answer_text.lower() == "none" or 
        answer_text.lower() == ""
    )
    
    # Handle empty true_objects (when the correct answer is that there are no answers)
    if not true_objects or len(true_objects) == 0:
        # If the model correctly indicated no answers, it's correct
        if is_empty_answer:
            return {
                "extracted_answer": answer_text,
                "tp_items": [],
                "fp_items": [],
                "fn_items": [],
                "quality": "correct" if has_think_tags else "failed",
                "precision": 1.0,
                "recall": 1.0,
                "f1": 1.0
            }
        else:
            # No ground truth but some predictions - all false positives
            generated_objects = [obj.strip() for obj in answer_text.split(",") if obj.strip()]
            return {
                "extracted_answer": answer_text,
                "tp_items": [],
                "fp_items": generated_objects,
                "fn_items": [],
                "quality": "wrong" if has_think_tags else "failed",
                "precision": 0.0,
                "recall": 1.0,  # Recalled everything (nothing) correctly
                "f1": 0.0
            }
    
    # Here we handle when there ARE true answers expected
    # If model gives empty answer when there should be answers
    if is_empty_answer:
        return {
            "extracted_answer": answer_text,
            "tp_items": [],
            "fp_items": [],
            "fn_items": true_objects,  # All true items were missed
            "quality": "wrong" if has_think_tags else "failed",  # Changed from "incomplete" to "wrong"
            "precision": 1.0,  # Everything we predicted (nothing) was correct
            "recall": 0.0,     # We failed to recall any true answers
            "f1": 0.0
        }
    
    # Normal case: both predicted and true answers exist
    # Normalize objects for comparison
    normalized_true_objects = [obj.lower().strip() for obj in true_objects] if normalize else list(true_objects)
    
    # Split answer text by commas and normalize
    generated_objects = [
        obj.strip() for obj in answer_text.split(",") 
        if obj.strip() and obj.strip().lower() != "none"
    ]
    
    normalized_generated_objects = [obj.lower() for obj in generated_objects] if normalize else list(generated_objects)
    
    # Find matches and populate TP, FP, FN lists
    tp_items = []  # Correctly found items
    matched_indices = set()  # To track which true objects have been matched
    
    # Determine if this is a numeric relation
    relation_type = RELATION_TYPE.get(relation, "string") if relation else "string"
    is_numeric = (relation_type == "numeric")
    
    if is_numeric:
        # Use numerical tolerance matching for numeric relations
        for i, gen_obj in enumerate(generated_objects):
            try:
                gen_num = float(gen_obj.strip())
                for j, true_obj in enumerate(true_objects):
                    if j in matched_indices:
                        continue  # Skip already matched true objects
                    try:
                        true_num = float(true_obj)
                        # Apply 5% tolerance for numerical comparisons
                        if abs(gen_num - true_num) / max(abs(true_num), 1e-8) <= tolerance:
                            tp_items.append(generated_objects[i])
                            matched_indices.add(j)
                            break
                    except (ValueError, TypeError):
                        continue
            except (ValueError, TypeError):
                continue
    else:
        # Use string-based matching for non-numeric relations
        # First pass: exact matches
        for i, gen_obj in enumerate(normalized_generated_objects):
            for j, true_obj in enumerate(normalized_true_objects):
                if j in matched_indices:
                    continue  # Skip already matched true objects
                    
                if gen_obj == true_obj:
                    # Store the original non-normalized versions
                    tp_items.append(generated_objects[i])
                    matched_indices.add(j)
                    break
        
        # Second pass: partial matches for items not already matched
        for i, gen_obj in enumerate(normalized_generated_objects):
            if generated_objects[i] in tp_items:
                continue  # Skip already matched generated objects
                
            for j, true_obj in enumerate(normalized_true_objects):
                if j in matched_indices:
                    continue  # Skip already matched true objects
                    
                # Check for partial matches (if true object is contained in generated or vice versa)
                if (gen_obj in true_obj) or (true_obj in gen_obj):
                    # Store the original non-normalized versions
                    tp_items.append(generated_objects[i])
                    matched_indices.add(j)
                    break
    
    # FP = generated objects not in TP (hallucinations)
    fp_items = [obj for obj in generated_objects if obj not in tp_items]
    
    # FN = true objects that weren't matched (missed)
    fn_items = [true_objects[i] for i in range(len(true_objects)) if i not in matched_indices]
    
    # Calculate precision, recall, F1
    tp_count = len(tp_items)
    fp_count = len(fp_items)
    fn_count = len(fn_items)
    
    precision = tp_count / (tp_count + fp_count) if (tp_count + fp_count) > 0 else 0
    recall = tp_count / (tp_count + fn_count) if (tp_count + fn_count) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    
    # Classify answer quality
    quality = classify_answer_quality(tp_items, fp_items, fn_items, has_think_tags)
    
    return {
        "extracted_answer": answer_text,
        "tp_items": tp_items,  # List of correctly found items
        "fp_items": fp_items,  # List of hallucinated items
        "fn_items": fn_items,  # List of missed items
        "quality": quality,    # Classification of answer quality
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

def process_synthetic_cot_results(train_df, generations, mode="help"):
    """
    Process synthetic CoT generation results, adding evaluation metrics.
    This function is intended to be called as a separate post-processing step,
    not directly from synthetic_cot.py.
    
    Args:
        train_df: DataFrame with original training data (including ground truth)
        generations: List of generated texts
        mode: Generation mode ("help" or "nohelp")
        
    Returns:
        pd.DataFrame: Enhanced DataFrame with generation results and metrics
    """
    import pandas as pd
    
    # Initialize results DataFrame with original data
    results_df = train_df.copy()
    
    # Add generations column if it doesn't already exist
    if "CoT" not in results_df.columns:
        results_df["CoT"] = generations
    
    # Add columns for evaluation metrics
    metrics_columns = [
        "extracted_answer", "tp_items", "fp_items", "fn_items", 
        "quality", "precision", "recall", "f1"
    ]
    for col in metrics_columns:
        results_df[col] = None
    
    # Evaluate each generation
    for i, row in results_df.iterrows():
        # Get ground truth
        true_objects = eval(row["ObjectEntities"])
        
        # Evaluate generation
        metrics = evaluate_generated_answer(
            generated_text=row["CoT"],
            true_objects=true_objects,
            normalize=True,
            extract_answer=(mode == "nohelp"),  # Only extract answer in nohelp mode
            require_think_tags=(mode == "nohelp"),  # Require think tags in nohelp mode
            relation=row["Relation"],
            tolerance=0.05
        )
        
        # Update DataFrame with metrics
        for col in metrics_columns:
            results_df.at[i, col] = metrics[col]
    
    # Calculate aggregate metrics for display
    avg_precision = results_df["precision"].mean()
    avg_recall = results_df["recall"].mean()
    avg_f1 = results_df["f1"].mean()
    
    # Display summary
    print(f"\nEvaluation Summary ({mode} mode):")
    print(f"  Average Precision: {avg_precision:.3f}")
    print(f"  Average Recall: {avg_recall:.3f}")
    print(f"  Average F1: {avg_f1:.3f}")
    
    return results_df
